schema_version: 1

context:
  name: azure-mgmt-eventhub
  version: 10.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-eventhub-${{ version }}.zip
  sha256: 319aa1481930ca9bc479f86811610fb0150589d5980fba805fa79d7010c34920

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.0,<2.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure.mgmt.eventhub
        - azure.mgmt.eventhub.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Event Hub Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
